### ISSUE TITLE
Move Admin Page to /admin

### ISSUE THREAD

**Issue by n2o** [n2o/url-shortener#13]
For easier deployment, it is necessary, that we change the Admin / Manage-Page to /admin. So, a "Catchall"-Controller can resolve the short URLs and we can put `/admin` for administration behind a HTTP-Basic Auth Wall.

Otherwise we need Spring Security, but renaming the Constructor and using HTTP Basic Auth on the deployment server should be sufficient.

**Comment by iTitus** [comment]
We need some safeguarding then, so that no short url is accessible via `/admin`. This would either destroy admin access or destroy a `/admin` short link.

**Comment by n2o** [comment]
Jep, and it should not be being produced by the automatical abbreviation creator.

**Comment by iTitus** [comment]
Partially closed by #14 
Still needs the auth & route change

**Comment by n2o** [comment]
Fixed in #17
