### ISSUE TITLE
"Quick-Link" feature

### ISSUE THREAD

**Issue by matlorr** [n2o/url-shortener#3]
Hello,

I never really contributed to a project before so if this post is out of place here please tell me.

I find this project interesting and I think the addition of an "quick link"-option would be an interesting feature. The functionality, at least as I imagined it, would be that the link you want to create would be generated out of the original link e.g "https://www.google.com" would be shortened to "localhost:8080/google" or "localhost:8080/ggl" latter option would be more useful for longer urls so they actually get shortened. This feature would be useful in creating short term use links which don't necessarily need an elaborate appearance e.g for links referring to surveys or polls.

As for the issues to overcome:

- Generating abbreviation from given Link possibly with max. char length of ten

- Abbreviation of longer links into shortened links without vowels (google -> ggl) 

- (possible) addition of a function to delete all "quick links"

Hopefully this idea can make a nice addition.

**Comment by mkasimd** [comment]
I have just implemented your suggestion, though without automatically adding the abbreviation, but suggesting an available abbreviation. As you suggested, I used the removal of vowels and the TLD as the method to obtain a suitable abbreviation.

As there can be conflicts, e.g.:
goggle.com -> gggl
giggle.com -> gggl

I added a unique integer behind the abbreviation if it already exists

The user still has to confirm that he's okay with the abbreviation before the abbreviation is added as a short URL.

**Comment by matlorr** [comment]
Thank you for implementing it! I will make sure to check it out on my machine. 
Yes, haven't thought about the abbreviation conflict for similar url but I think yours a good solution.
Also the conformation page is a very useful one.
hopefully I can make some contributions soon too, I am kinda very slow at coding at the moment.

**Comment by mkasimd** [comment]
I noticed that adding multiple abbreviations for the same URL is possible. To avoid that, I added a duplication prevention system in branch [duplicate-prevention](https://github.com/mkasimd/url-shortener/tree/duplicate-prevention).

If entry exists, that version displays an error message with the already existing abbreviation instead of allowing multiple abbreviations for the same URL.

As it builds upon the code that adds auto-suggestions, I didn't send a PR for it yet.

Feel free to check it out as well.

**Comment by matlorr** [comment]
Ok will do! Also I added that if urls with the scheme "https://www.xy.com" are added the "www." part wont be added into the abbreviation. Tho I don't know how to commit such a minor change, should I add a seperate pull req. for this one ? Its just one if-statement haha.

**Comment by mkasimd** [comment]
I don't know. You can send a new PR maybe. Or you can send a PR into my
master branch and it should be committed too.

Choose whichever you want.

matlorr <notifications@github.com> schrieb am Mo., 25. Nov. 2019, 09:47:

**Comment by matlorr** [comment]
ok will do one of those.
First time participating

**Comment by n2o** [comment]
Thanks for your help, the changes are now merged, see #6
