### ISSUE TITLE
Feature Request: URL Expansion 

### ISSUE THREAD

**Issue by erdidogan** [n2o/url-shortener#36]
I would like to suggest a new feature to this project.  A new functionality which supports to expand any type of short url.

Example : 

-> Given Input : https://bit.ly/2OLL4ZN
-> Expected Output: https://www.google.com/

If you like this feature and decide add it, I will be more than happy to work on it.  

Thanks,
Erdi

**Comment by n2o** [comment]
Hi, thanks for the interest. I do not yet see why this should fit into this project. Can you explain it a bit more please?

**Comment by erdidogan** [comment]
Hi, thanks for your quick response. With this functionality an authenticated user will have two options to use this application; First option is create shortened url and second option is to view original url by expanding a short url. This feature might seems like not a good fit into project but I though extending project functionality would be good for to cover both url based operations ( shorten, expand).

Thanks,
Erdi
